"""
Django settings for writerprj project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from django.conf import settings

if not settings.DEBUG:
    import os

    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    def get_env_variable(var_name):
        """Get the environment variable or return exception """
        try:
            return os.environ[var_name]
        except KeyError:
            error_msg = "Set the %s environment variable" % var_name
            raise ImproperlyConfigured(error_msg)

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = get_env_variable("SECRET_KEY")

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

    ADMINS = (("Don", "don@zobasoft.biz"),)
    ALLOWED_HOSTS = ['zobasoft.biz', 'www.zobasoft.biz']

    # From blog at:  https://www.codingforentrepreneurs.com/blog/configure-email-in-django/
    EMAIL_HOST = 'smtp.gmail.com'  # 'smtp.gmail.com' for gmail
    EMAIL_HOST_USER = 'yourusername@youremail.com'
    EMAIL_HOST_PASSWORD = 'your password'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = 'don@zobasoft.biz'
    SERVER_EMAIL = 'don@zobasoft.biz'

    ADMINS = (
        ('You', 'you@email.com'),
    )
    MANAGERS = ADMINS

    # Application definition

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.sites',
        'crispy_forms',
        'csp',
        'writerhome',
        'simple_pagination',
        'django_blog_it.django_blog_it',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'csp.middleware.CSPMiddleware',
    ]

    ROOT_URLCONF = 'writerprj.urls'
    LOGIN_URL = '/login/'
    DEFAULT_HOST = 'www'
    # Disquss details
    DISQUS_SHORTNAME="www-zobasoft-biz-example-1"


    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates')],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'writerprj.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/1.11/ref/settings/#databases

    from .db_password import DBPASS

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.path.join(BASE_DIR, 'writerprj.db'),
            'USER': 'zobadeploy',
            'PASSWORD': DBPASS,
        }
    }


    # Password validation
    # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/1.11/topics/i18n/
    LANGUAGE_CODE = 'en-us'
    TIME_ZONE = 'UTC'
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.11/howto/static-files/

    STATIC_URL = '/static/'
    STATIC_ROOT = '/home/zobadeploy/webapps/writerprj_static/'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/home/zobadeploy/webapps/writerprj_media/'
