# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriterPrjAllBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('datePub', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descr', models.TextField(blank=True, max_length=2048)),
                ('abstract', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
