# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writerhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprjallbooks',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
