# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import writerhome.validators


class Migration(migrations.Migration):

    dependencies = [
        ('writerhome', '0002_writerprjallbooks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerprjallbooks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[writerhome.validators.validate_price]),
        ),
    ]
