# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writerhome', '0004_writerprjallbooks_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprjallbooks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
