# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writerhome', '0005_writerprjallbooks_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprjallbooks',
            name='is_active',
        ),
        migrations.AddField(
            model_name='writerprjallbooks',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writerprjallbooks',
            name='activation_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
