# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writerhome', '0007_writerprjallbooks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprjallbooks',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='writerprjallbooks',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
